### ISSUE TITLE
OSError: /home/xyz/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by Rajkumarsaswamy** [dvl-tum/mot_neural_solver#39]
I followed until step 5 in setup. 

I ran into error when i executed:  python scripts/evaluate.py. Could you help me?

Traceback (most recent call last):
  File "scripts/evaluate.py", line 9, in <module>
    from mot_neural_solver.pl_module.pl_module import MOTNeuralSolver
  File "/home/rajkumar/mot_neural_solver/src/mot_neural_solver/pl_module/pl_module.py", line 6, in <module>
    from torch_geometric.data import DataLoader
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/rajkumar/.local/lib/python3.6/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/rajkumar/anaconda3/envs/mot_neural_solver/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by Rajkumarsaswamy** [comment]
I solved the issue by installing torch and torch vision directly and not by conda. As conda installs both CPU and GPU version

pip install https://download.pytorch.org/whl/cu101/torch-1.5.0%2Bcu101-cp36-cp36m-linux_x86_64.whl
pip install https://download.pytorch.org/whl/cu101/torchvision-0.6.0%2Bcu101-cp36-cp36m-linux_x86_64.whl
